// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PVaESishzU1UrYTVIJ8MXRcvTNX1Bxo',
    appId: '1:1051230335697:web:071375004f51f2c3d64bf0',
    messagingSenderId: '1051230335697',
    projectId: 'waroenggo-126af',
    authDomain: 'waroenggo-126af.firebaseapp.com',
    storageBucket: 'waroenggo-126af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLGV5TIpcxhcW7c4kzUBJizsPGF8VkDwg',
    appId: '1:1051230335697:android:6e33f959e60255a6d64bf0',
    messagingSenderId: '1051230335697',
    projectId: 'waroenggo-126af',
    storageBucket: 'waroenggo-126af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6o6geuWqDueIGj4PRNpTzczufRLw4S7w',
    appId: '1:1051230335697:ios:8c0e20acc66f21f8d64bf0',
    messagingSenderId: '1051230335697',
    projectId: 'waroenggo-126af',
    storageBucket: 'waroenggo-126af.firebasestorage.app',
    iosBundleId: 'com.example.waroengGo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6o6geuWqDueIGj4PRNpTzczufRLw4S7w',
    appId: '1:1051230335697:ios:8c0e20acc66f21f8d64bf0',
    messagingSenderId: '1051230335697',
    projectId: 'waroenggo-126af',
    storageBucket: 'waroenggo-126af.firebasestorage.app',
    iosBundleId: 'com.example.waroengGo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PVaESishzU1UrYTVIJ8MXRcvTNX1Bxo',
    appId: '1:1051230335697:web:566feb5255f92977d64bf0',
    messagingSenderId: '1051230335697',
    projectId: 'waroenggo-126af',
    authDomain: 'waroenggo-126af.firebaseapp.com',
    storageBucket: 'waroenggo-126af.firebasestorage.app',
  );

}